[package]
name = "plein_air"
version = "0.1.0"
authors = ["Jack Jennings <jack@standard-library.com>"]

[dependencies]
rocket = "0.4.0"
regex = "1"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["tera_templates"]
